CREATE TABLE [dbo].[Logs] (
	  [Id] [int] IDENTITY(1,1) NOT NULL,
	  [Application] NVARCHAR(50) NOT NULL,
	  [CreateDate] DATETIME2 NOT NULL,
	  [Level] NVARCHAR(50) NOT NULL,
	  [Message] NVARCHAR(MAX) NOT NULL,
	  [UserEmail] NVARCHAR(320) NULL,
	  [SessionId] NVARCHAR(250) NULL,
	  [Url] NVARCHAR(250) NULL,
	  [Action] NVARCHAR(250) NULL,
	  [Logger] NVARCHAR(250) NULL,
	  [Exception] NVARCHAR(MAX) NULL,
    CONSTRAINT [PK_dbo.Logs] PRIMARY KEY CLUSTERED ([Id] ASC)
      WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
  ) ON [PRIMARY]